server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "5432"
  user: "campus_user"
  password: "campus_114514"
  dbname: "campus_delivery"
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 100